version: 0.0
os: linux
files:
  - source: src
    destination: /home/ec2-user
#  - source:
#    destination:
#hooks:
#  ApplicationStop:
#    - location:
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas:
#  BeforeInstall:
#    - location:
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas:
#  AfterInstall:
#    - location:
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas:
#  ApplicationStart:
#    - location:
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas:
#  ValidateService:
#    - location:
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas: