version: 0.0
os: linux
files:
  - source: src
    destination: /home/ec2-user
hooks:
#  ApplicationStop:
#    - location:
#      timeout:
#      runas:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
#  ValidateService:
#    - location:
#      timeout:
#      runas:
#    - location:
#      timeout:
#      runas: