--- 
files: 
  - 
    destination: /
    source: src
hooks: 
  ApplicationStart: 
    - 
      location: scripts/application_start.sh
      runas: root
      timeout: 300
  ApplicationStop: 
    - 
      location: scripts/application_stop.sh
      runas: root
      timeout: 300
  BeforeInstall: 
    - 
      location: scripts/install_dependencies.sh
      runas: root
      timeout: 300
os: linux
version: 0.0
